### ISSUE TITLE
Question: how to use with gulp-typedoc?

### ISSUE THREAD

**Issue by tony--** [gdelmas/typedoc-plugin-sourcefile-url#1]
Is it possible to use this in conjunction with [gulp-typedoc](https://github.com/rogierschouten/gulp-typedoc)?  It's not possible to specify sourcefile-url-prefix in the typedoc options

**Comment by gdelmas** [comment]
i have not tested. it looks like the options object is passed through to typedoc (https://github.com/rogierschouten/gulp-typedoc/blob/master/index.js#L48).

why is it not possible to specify the `sourcefile-url-prefix` in the gulp typedoc options? what is the error?

**Comment by tony--** [comment]
Options get passed to typedoc as an object literal.  
Hyphens are not allowed in javascript variable names.  
Trying to specify 
```
var typedoc = require("gulp-typedoc");

gulp.task("typedoc", function() {
	return gulp
		.src(["data/*.ts"])
		.pipe(typedoc({
			// TypeScript options (see typescript docs)
			module: "commonjs",
			target: "es5",
			includeDeclarations: true,

			// Output options (see typedoc docs)
			out: "./out",
			json: "output/to/file.json",

			// TypeDoc options (see typedoc docs)
			name: "my-project",
			theme: "/path/to/my/theme",
			plugins: ["my", "plugins"],
			ignoreCompilerErrors: false,
			version: true,
			sourcefile-url-prefix: 'https://github.mycompany.com/my-project/my-repo'
		}))
	;
});
```
results in
```SyntaxError: Unexpected token -```

**Comment by gdelmas** [comment]
you should be able to pass it like:

    'sourcefile-url-prefix': 'https://github.mycompany.com/my-project/my-repo'

**Comment by tony--** [comment]
I tried that and it comes in as undefined.  
I added a console.log inside SourcefileUrlMapPlugin.js to verify that the plugin is loading and check the value:
```console.log('urlPrefix:'+urlPrefix);```

Thanks for getting back to me so quickly about this!

**Comment by gdelmas** [comment]
can you also debug if the option arrived in typedoc? it would be interesting to know where it gets lost. can you also check if the option would go through without the hyphens.

**Comment by tony--** [comment]
I tried replacing the hyphens with underscores and it did not come through.
It does not seem like the options are coming through from gulp as expected by this plugin.
I tried logging some of the other options and they were undefined.
I wonder if there is some other interface besides ```this.application.options```?
Sorry I'm not much help.

**Comment by gdelmas** [comment]
can you check if this is a general issue with typedoc and gulp? there are some other plugins here: https://www.npmjs.com/browse/keyword/typedocplugin

**Comment by tony--** [comment]
I added a bunch of logging to try to figure out what is happening.
I noticed that this plugin's options are not loaded at the time that ```initialize``` is called on the plugin, but they are loaded by the time of ```onEndResolve```.
I'm not sure if this is related to gulp, actually.

Moving the code that initializes ```mappings``` into ```onEndResolve``` fixes this.

I'll open a PR so you can see, then you can decide if you agree it makes sense!

**Comment by gdelmas** [comment]
interesting. thank you. probably the CLI path in typedoc is different than the application path. i will connect it to a debugger.
