### ISSUE TITLE
Deprecated / error The plugin typedoc-plugin-sourcefile-url could not be loaded.

### ISSUE THREAD

**Issue by pakkographic** [gdelmas/typedoc-plugin-sourcefile-url#21]
extending this issue: https://github.com/gdelmas/typedoc-plugin-sourcefile-url/issues/18
Maybe another issue will wake up gdelmas?

In the hope of getting an update.

**Comment by gdelmas** [comment]
thanks for your last effort in reaching out. as i have not been using this plugin for a while, I am deprecating it. sorry i can't help with fixing it. you are welcome to fork

**Comment by greenlihui** [comment]
typedoc has offered an option which does the similar thing: https://typedoc.org/options/input/#sourcelinktemplate

**Comment by pakkographic** [comment]
Yeah I know this for a long time, I just didn't close the issue, thanks though
