### ISSUE TITLE
Link to master branch instead of specific commit.

### ISSUE THREAD

**Issue by danmarshall** [gdelmas/typedoc-plugin-sourcefile-url#4]
Hello, thanks for this plugin. Is there a way to have the source links go to the `master` branch instead of the commit ID? I check in my generated files, and having the commitID makes my changeset very noisy.

**Comment by gdelmas** [comment]
not sure where you get the commit id from. this plugin is not adding this. maybe this is from your file path?

**Comment by danmarshall** [comment]
I'm also not sure how Typedoc gets the commit id. Perhaps I can use the regex feature to find and replace it.

**Comment by gdelmas** [comment]
although it was not intended for this, it might work. otherwise check without the plugin how typedoc structures your files.
