### ISSUE TITLE
plugin breaks in typedoc 0.14

### ISSUE THREAD

**Issue by Roaders** [gdelmas/typedoc-plugin-sourcefile-url#5]
when typedoc is updated to 0.14:

```
Error: The plugin ...typedoc-plugin-sourcefile-url could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
```
(above typed not copy-pasted fyi)

**Comment by nikordev** [comment]
Hi, try to change tsconfig target to `es6`

**Comment by csskevin** [comment]
Hi,
I have the same issue
Nope, that doesn't change anything to set the target to es6. 
By default I have `ESNext`. I changed it to `es6` as you said, but it did not work either.
My `tsconfig.json` looks like this:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ESNext",
    "jsx": "react",
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

**Comment by nikordev** [comment]
@csskevin Hi, i made fork with some changes, please try it.
It's work for me without problems under `typedoc@0.14.2` and `typescript@3.2.4`

**Comment by dws-dave** [comment]
we've been using [patch-package](https://www.npmjs.com/package/patch-package) to avoid forking, although it's a bit grim: https://github.com/dwstech/muster/blob/develop/patches/typedoc-plugin-sourcefile-url%2B1.0.3.patch

**Comment by sirisak1985** [comment]
issue

**Comment by gdelmas** [comment]
sorry. havn't had the time to look at it yet but hope to definitively address this with the next update in one to two weeks.
