### ISSUE TITLE
this plugin can't work in typedoc 0.15

### ISSUE THREAD

**Issue by zyziyun** [gdelmas/typedoc-plugin-sourcefile-url#8]
One of the reasons is this：https://github.com/TypeStrong/typedoc/issues/1097
But if I solved this problem, this plugin still doesn't work.

**Comment by aaronfg** [comment]
Hope PR #10  gets approved. Just started using this plugin and noticed it wasn't working from the same abort message as mentioned in that PR

**Comment by gdelmas** [comment]
fixed in version 1.0.6
